#!/bin/ksh
 
set -x

# HOMEdir set in qsub job

. $HOMEdir/jobs/JHAFS_ENVIR
. $WORKdir/${CYCLE}/intercom/experiment.${CYCLE}

export MODULES=${PREREQSscript}

#######################################################################
#
# Execute the respective BUFR preparation scripts in accordance with
# the user specifications; launch the following tasks:
#
# (1) Create PREFBUFR-formatted file for the NOAA/AOML/HRD TEMP-DROP 
#     sonde observations.
#
# (2) Create PREPBUFR-formatted file for the NOAA/AOML/HRD G-IV 
#     tail-Doppler radar (TDR) u- and v-wind observations.

#######################################################################

# Create local sub-directories.

mkdir -p ${COMROOT}/bufrprep
mkdir -p ${EXPTROOT}/bufrprep

# Get processor id (pid).

export pid=$$

# Process NOAA/AOML/HRD dropsondes with drift calculations.

if [ $PREPBUFRhsa = 1 ]; then
    ${SCRIPTdir}/exhafs_bufrprep_hsa.sh
fi # [ $PREPBUFRhsa = 1 ]

# Process NOAA/AOML/HRD G-IV tail-Doppler radar (TDR) u- and v-winds.

if [ $PREPBUFRgivtdruv = 1 ]; then
    ${SCRIPTdir}/exhafs_bufrprep_givtdruv.sh
fi # [ $PREPBUFRgivtdruv = 1 ]
